# Generated by Django 4.1.5 on 2023-02-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_additionalpicture_is_vite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, max_length=303, null=True),
        ),
    ]
